### ISSUE TITLE
[BS-pratybos]: Panašiais→ Panašiai

### ISSUE THREAD

**Issue by Amaria24** [mokymai/taisymai-2023#123]
1. **Dalykas:** BS-2023
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/pratybos/s04.html
4. **Glaustai aprašykite netikslumą:**  Rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** šalia kodo yra tekstas – kodo ir jo rezultatų paaiškinimai – natūralia (lietuvių, anglų ar kita) kalba. **Panašiais**, kaip tai daroma knygose.
6. **Netikslumo tekstas:** Panašiais
7. **Siūlomas taisymo tekstas:** Panašiai
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![Untitled2](https://user-images.githubusercontent.com/124585434/221430352-5bab9a1f-44ce-49eb-b68e-0398d868c7b9.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by Amaria24** [comment]
Sukūriau kaip klaidą, bet tik paskui pamačiau, kad jau buvo užregistruota, todėl nežinau, kaip panaikinti.

**Comment by GegznaV** [comment]
Kopija:

- #111
