### ISSUE TITLE
[BS-teorija]: tikri jie iš tiesų → tikri, kad (skyrybos klaida IR praleistas žodis)

### ISSUE THREAD

**Issue by deimpo** [mokymai/taisymai-2023#128]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/ht-ivadas.html
4. **Glaustai aprašykite netikslumą:**  skyrybos klaida ir praleistas žodis:) (mačiau vieną taisymą tik dėl žodžio, bet palikta klaida dėl praleisto kablelio)

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Todėl net ir matydami skirtumus imtyje, negalime būti visiškai tikri jie iš tiesų egzistuoja. 
6. **Netikslumo tekstas:**  tikri jie iš tiesų egzistuoja.
7. **Siūlomas taisymo tekstas:**  tikri, kad jie iš tiesų egzistuoja.
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![klaida1](https://github.com/mokymai/taisymai-2023/assets/144257898/ae09dfaa-ce24-4a53-af85-a936a0b3ca3d)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dublikatas: 
- #126
