### ISSUE TITLE
[BS-teorija]: sukaptojo → sukauptojo (rašyba)

### ISSUE THREAD

**Issue by TaurasRad** [mokymai/taisymai-2023#139]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** Teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** (https://mokymai.github.io/biostatistika/grafikai.html)
4. **Glaustai aprašykite netikslumą:** Rašybos klaida - sukaptojo ir danžnio 

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Empirinio sukaptojo santykinio danžnio diagrama  
6. **Netikslumo tekstas:**  sukaptojo danžnio 
7. **Siūlomas taisymo tekstas:** sukauptojo dažnio
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![BS](https://user-images.githubusercontent.com/124564607/221563106-ef9cc750-1dcf-4001-8876-db5f7460f35d.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Atkreipkite dėmesį, kaip taisyklingai pateikti temos pavadinimą (jau pataisiau)
