### ISSUE TITLE
Tidyverse pagrindai pradedantiesiems: šiuose → šiose 

### ISSUE THREAD

**Issue by VanesaKariunaite** [mokymai/taisymai-2023#170]
-->
 
1. **Dalykas:** ... 
2. **Netikslumo vieta:** ... Tidyverse pagrindai pradedantiesiems
3. **Bylos pavadinimas ar nuoroda (URL):** ... file:///C:/Users/37064/OneDrive%20-%20Vilnius%20University/vu/biostatistika/pratybos/BS-2023--S06--intro-tidyverse/BS-2023--S06--intro-tidyverse/HTML/03--LT--tidyverse--for-beginners--exercises.html
4. **Glaustai aprašykite netikslumą:**  ... rašybos klaida
 
5. **Nukopijuokite visą sakinį su netikslumu:** Šiuose užduotyse jums reikės kodą rašyti (A) būdu (neatnaujinti lentelių), bet įprastinės duomenų analizės metu dažnai reikia (B) būdu parašyto kodo.

6. **Netikslumo tekstas:** ...
7. **Siūlomas taisymo tekstas:** ...
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
... 

![image](https://user-images.githubusercontent.com/124563154/226391708-56dab221-77be-4381-89c4-cf7d691c7aec.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
@VanesaKariunaite, prašau sutvarkyti šio pranešimo pavadinimą.
