### ISSUE TITLE
statistiniai-rodikliai-SABLONAS Excel failas. interpratacija taisoma į interpretacija nr. 2

### ISSUE THREAD

**Issue by beatute123** [mokymai/taisymai-2023#24]
statistiniai-rodikliai-SABLONAS Excel failas. 2 paskaita

netikslumas interpratacija → taisymas interpretacija

*Dalykas: BS-2023
**Netikslumo vieta: statistiniai-rodikliai-SABLONAS Excel failas. 2 paskaita
**Bylos pavadinimas ar nuoroda (URL): statistiniai-rodikliai-SABLONAS Excel failas. 2 paskaita
**Glaustai aprašykite netikslumą: netikslumas interpratacija → taisymas interpretacija
**Nukopijuokite visą sakinį su netikslumu: Interpratacija (subjektyvi)
Rekomenduojama pacituoti šaltinį, kuo grindžiama šį interpretacija
**Netikslumo tekstas: Interpratacija (subjektyvi)
Rekomenduojama pacituoti šaltinį, kuo grindžiama šį interpretacija
**Siūlomas taisymo tekstas: interpretacija
Ekrano nuotrauka („Screenshots“) su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/124630045/218542755-4c4d3afc-8f4e-4810-bfee-76633dd2af42.png)

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Kopijavimo klaida:

- #23
