### ISSUE TITLE
[Pratybų svetainė]: trūksta kablelio išskiriant šalutinį sakinį (po žodžio "teisingai")

### ISSUE THREAD

**Issue by lukrecijak** [mokymai/taisymai-2023#27]
1. **Dalykas:** BS-2023
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/pratybos/s02.html#uzduotys-s02
4. **Glaustai aprašykite netikslumą:**  Skyrybos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** suvesti teisingai ir kiek galima labiau 
6. **Netikslumo tekstas:** Imamasi priemonių, kad duomenys butų suvesti teisingai ir kiek galima labiau apsisaugoma nuo duomenų suvedimo klaidų.
7. **Siūlomas taisymo tekstas:** Imamasi priemonių, kad duomenys butų suvesti teisingai, ir kiek galima labiau apsisaugoma nuo duomenų suvedimo klaidų.
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/125295883/219855174-9175a0f2-0e18-4766-8e70-f927fd28ddf4.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Čia tas pats šalutinis sakinys, nsakantis, kam reikalingos priemonės: "priemonių, kad ... būtų suvesti ... ir (būtų) apsisaugoma"
