### ISSUE TITLE
[Pratybų svetainė]: trūksta kablelio išskiriant šalutinį sakinį (po žodžių "funkcijos" ir "skyriuje")

### ISSUE THREAD

**Issue by lukrecijak** [mokymai/taisymai-2023#29]
1. **Dalykas:** BS-2023
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/pratybos/s02.html#uzduotys-s02
4. **Glaustai aprašykite netikslumą:**  Skyrybos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Kitos funkcijos kurias apžvelgsime šiame skyriuje 
6. **Netikslumo tekstas:** Kitos funkcijos kurias apžvelgsime šiame skyriuje yra View(), head(), tail(), any(is.na()) ir colSums(is.na()).
7. **Siūlomas taisymo tekstas:** Kitos funkcijos, kurias apžvelgsime šiame skyriuje, yra View(), head(), tail(), any(is.na()) ir colSums(is.na()).
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/125295883/219857657-f03b75d6-fd31-40b3-927f-fbb6e379f7b6.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Šita klaida medžiagoje buvo nuo 2020 m. Dėkui, kad pastebėjote.
