### ISSUE TITLE
[Biostatistika]: m“atomas → matomas

### ISSUE THREAD

**Issue by Kaciukukebabai** [mokymai/taisymai-2023#3]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** Biostatistikos teorijos svetainė (`mokymai.github.io`)
3. **Nuoroda (URL):** https://mokymai.github.io/programa-r/diegimas.html#diegti-programas
4. **Glaustai aprašykite netikslumą:**  Rašybos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** rašyti nereikia, šis simbolis tiesiog m“atomas komandų 
6. **Netikslumo tekstas:**  m“atomas
7. **Siūlomas taisymo tekstas:**  matomas
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![image](https://user-images.githubusercontent.com/32066050/216932093-83b9df79-6dc6-40a6-a64d-71a4445834df.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Pirmas pranešė #1, bet jum įskaitysiu, nes buvo pranešta ne pagal taisykles (pavadinimas neatspindėjo esmės)
