### ISSUE TITLE
[Video]: k = 2→ k = 5

### ISSUE THREAD

**Issue by Kaciukukebabai** [mokymai/taisymai-2023#41]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** P02-04 10:45-11:05
3. **Bylos pavadinimas ar nuoroda (URL):** https://youtu.be/qFg0J71-8H8?list=PLLE8FSeLAY2rFoQE6M91K3ft5bB_cSEYT&t=657
4. **Glaustai aprašykite netikslumą:**  Skaičiavimo klaida (Yra 5 skirtingos reikšmės, todėl k turėtų būti 5)
 
5. **Nukopijuokite visą sakinį su netikslumu:** 

6. **Netikslumo tekstas:** k = 2
7. **Siūlomas taisymo tekstas:** k = 5
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/32066050/219986098-52da45f0-030e-41ac-b4de-619336b08350.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Skaidrėse ištaisyta.
