### ISSUE TITLE
P03-1 (v1.4) sk67: rašybos klaida --> žodis "dispersija"

### ISSUE THREAD

**Issue by Austutute** [mokymai/taisymai-2023#63]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P03-1 v1.4 
4. **Skaidrės numeris:** 67 
5. **Glaustai aprašykite netikslumą:** Pirmame punkte parašyta šaknis iš dispersija, manau turėtų būti "šaknis iš dispersijos"

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Šaknis iš dispersija 
7. **Netikslumo tekstas:** Šaknis iš dispersija
8. **Siūlomas taisymo tekstas:** Šaknis iš dispersijos
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta. 
![image](https://github.com/mokymai/taisymai-2023/assets/144160265/6b329a1f-986e-42cf-bc04-c523f6865d34)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėkui. O dabar dar užpildykite pranešimo pavadinimą taip, kad jis būtų informatyvus kitiems studentams.
