### ISSUE TITLE
P03-1 (v1.4) sk.58: rašybos klaida --> žodis "Galimas"

### ISSUE THREAD

**Issue by Austutute** [mokymai/taisymai-2023#64]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P03-1 v1.4 
4. **Skaidrės numeris:** 58
5. **Glaustai aprašykite netikslumą:** Rašybos klaida

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Galimas bet kokia
7. **Netikslumo tekstas:** Galimas bet kokia μ reikšmė
8. **Siūlomas taisymo tekstas:** Galima bet kokia μ reikšmė
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta. 
![image](https://github.com/mokymai/taisymai-2023/assets/144160265/8e1ed645-3756-466a-9cb6-3759e42ac7d1)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Atsižvelgti į šią pastabą https://github.com/mokymai/taisymai-2023/issues/63#issuecomment-1746443403
