### ISSUE TITLE
statistiniai-rodikliai-SABLONAS Excel failas v.1.4. rašybos klaida: korelacijos taisoma į koreliacijos nr.2

### ISSUE THREAD

**Issue by beatute123** [mokymai/taisymai-2023#76]
**Dalykas: BS-2023

**Netikslumo vieta: Spearman (Spyrmano) ranginės korelacijos koeficientas

**Bylos pavadinimas ar nuoroda (URL): statistiniai-rodikliai-SABLONAS Excel failas v.1.4.

**Glaustai aprašykite netikslumą: rašybos klaida korelacijos

**Nukopijuokite visą sakinį su netikslumu: Spearman (Spyrmano) ranginės korelacijos koeficientas

**Netikslumo tekstas: Spearman (Spyrmano) ranginės korelacijos koeficientas

**Siūlomas taisymo tekstas: korelacijos taisoma į koreliacijos
![image](https://user-images.githubusercontent.com/124630045/220441724-5606b1b0-3a8f-494f-81c5-1f3590f7e9fa.png)

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x ] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Kopijavimo klaida
