### ISSUE TITLE
[statistiniai-rodikliai-v1.4--SABLONAS]: rodiklis: rodo→ rodiklis rodo (skyryba)

### ISSUE THREAD

**Issue by KarolinaEigerd** [mokymai/taisymai-2023#77]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** Konkrečią duomenų reikšmę apibūdinantis rodiklis: rodo, kiek standartinių nuokrypių reikšmė yra nutolusi nuo vidurkio.
3. **Bylos pavadinimas ar nuoroda (URL):** statistiniai-rodikliai-v1.4--SABLONAS
4. **Glaustai aprašykite netikslumą:**  skyrybos klaida
 
5. **Nukopijuokite visą sakinį su netikslumu:** Konkrečią duomenų reikšmę apibūdinantis rodiklis: rodo, kiek standartinių nuokrypių reikšmė yra nutolusi nuo vidurkio.

6. **Netikslumo tekstas:**  rodiklis: rodo, kiek standartinių nuokrypių reikšmė yra nutolusi nuo vidurkio.
7. **Siūlomas taisymo tekstas:** rodiklis rodo, kiek standartinių nuokrypių reikšmė yra nutolusi nuo vidurkio.
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
... 

![ekrano4](https://user-images.githubusercontent.com/124563152/220442688-194e63be-7e3f-4b19-a45c-775748a65a1f.jpg)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Klaidos nematau.
