### ISSUE TITLE
[Biostatistika]: paskalbs → paskelbs (rašybos klaida)

### ISSUE THREAD

**Issue by beatute123** [mokymai/taisymai-2023#8]

**Comment by GegznaV** [comment]
@beatute123, ar galėtumėte patikslinti? Arba uždaryti klausimą, jei jis sukurtas netyčia?

**Comment by beatute123** [comment]
1. **Dalykas:** BS-2023 
2. **Netikslumo vieta:** Biostatistikos teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):   https://mokymai.github.io/programa-r/paskyros.html#datacamp-paskyra
4. **Glaustai aprašykite netikslumą: rašybos klaida - paskalbs
6. **Netikslumo tekstas: Prie kurso grupės prisijungti galėsite tik gavę el.laišką su pakvietimu. Datą, nuo kada visai grupei bus suteikta nemokama prieiga, dėstytojas paskalbs užsiėmimų metu. Nemokama prieiga galios 6 mėnesius. Atkreipkite dėmesį, kad prisijungimas prie „DataCamp“ jums yra visiškai nemokamas. Jei jums siūlys susimokėti, tai arba dar neatėjo reikiama data, arba nesuveikė prisijungimo nuoroda. Pati prisijungimo procedūra bus paaiškinta žemiau.
7. **Siūlomas taisymo tekstas: paskelbs
