### ISSUE TITLE
[Emokymai]: neveikianti nuoroda Grafikai kintamųjų porai → sutvarkyti nuorodą

### ISSUE THREAD

**Issue by Riimmma** [mokymai/taisymai-2023#81]
1. **Dalykas:** BS-2023
2. **Netikslumo vieta:** „Emokymai“ svetainė
3. **Nuoroda į resursą (URL):**[https://emokymai.vu.lt/course/view.php?id=341]
4. **Glaustai aprašykite netikslumą:** neveikianti nuoroda 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Grafikai kintamųjų porai 
6. **Netikslumo tekstas:** Neveikia nuoroda pavadinimu Grafikai kintamųjų porai
7. **Siūlomas taisymo tekstas:** Sutvarkyti nuorodą
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://github.com/mokymai/taisymai-2023/assets/144147168/c116ed14-02e5-4749-9bb8-8a0a08c40671) 

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
- #75
